import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { TelegramProvider } from '@/context/telegramContext'
import { NavProvider } from '@/context/navContext'
import { Nav } from '@/app/components/nav'
import Script from 'next/script'

const inter = Inter({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <head>
        <title>Tellme</title>
        <Script
          src='https://telegram.org/js/telegram-web-app.js'
          strategy='beforeInteractive'
        />
      </head>
      <body className={inter.className}>
        <TelegramProvider>
          <NavProvider>
            <AntdRegistry>
              {children}
              <Nav />
            </AntdRegistry>
          </NavProvider>
        </TelegramProvider>
      </body>
    </html>
  )
}